In [1]:
import numpy as np

In [2]:
print(np.__version__)
np.show_config()

1.15.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


In [3]:
Z=np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
print("%d bytes"%(Z.size*Z.itemsize))#内存大小
Z1=np.zeros(1000)
print(Z1.size,Z1.itemsize)
print("%d bytes"%(Z1.size*Z1.itemsize))#内存大小

80 bytes
1000 8
8000 bytes


In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [6]:
#单个赋值
Z=np.zeros(10)
Z[4]=1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
#范围值
Z=np.arange(10,40)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39]


In [8]:
Z1=np.arange(40)
Z2=Z[::-1]#逆转list
print(Z2)

[39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16
 15 14 13 12 11 10]


In [9]:
Z=np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
#找到非零索引
nz=np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [11]:
Z=np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
Z=np.random.random((3,3,3))
print(Z)

[[[0.70226445 0.68407901 0.75107723]
  [0.44323264 0.85832541 0.11452927]
  [0.50001544 0.65329763 0.70523943]]

 [[0.90294403 0.07970414 0.00143584]
  [0.77509028 0.33263394 0.4704104 ]
  [0.15018124 0.87304509 0.34598626]]

 [[0.15374332 0.15714272 0.34691463]
  [0.95542544 0.508436   0.65822816]
  [0.93746165 0.11626226 0.41816239]]]


In [13]:
Z=np.random.random((10,10))
Zmin,Zmax=Z.min(),Z.max()
print(Zmin,Zmax)

0.0014729824250683254 0.9971215341619958


In [14]:
Z=np.random.random(30)
m=Z.mean()
print(m)

0.5396586459238697


In [15]:
#范围换值
Z=np.ones((10,10))
Z[1:-1,1:-1]=0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [16]:
#pad...扩充
Z=np.ones((5,5))
Z=np.pad(Z,pad_width=2,mode="constant",constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [17]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.inf)
print(np.nan-np.nan)
print(0.3==0.1*3)
print(0.1*3)
print(type(0.1*3))
print(type(0.3))
a=0.1*3
b=0.3
print(a-b)

nan
False
False
inf
nan
False
0.30000000000000004
<class 'float'>
<class 'float'>
5.551115123125783e-17


In [18]:
#对角线上赋值
Z=np.diag(1+np.arange(4),k=-1)
print(Z)
Z=np.diag(1+np.arange(5),k=0)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [19]:
Z=np.zeros((8,8),dtype=int)
print(Z)
Z[1::2,::2]=1
Z[::2,1::2]=1
print(Z)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [20]:
#求一个numpy 中第i个值得下标
print(np.unravel_index(1,(6,7,8)))
print(np.unravel_index(2,(6,7,8)))
print(np.unravel_index(3,(6,7,8)))
print(np.unravel_index(10,(6,7,8)))
print(np.unravel_index(10,(10,10)))
print(np.unravel_index(11,(10,10)))

(0, 0, 1)
(0, 0, 2)
(0, 0, 3)
(0, 1, 2)
(1, 0)
(1, 1)


In [21]:
Z=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [22]:
#均值归一化
Z=np.random.random((5,5))
Zmax,Zmin=Z.max(),Z.min()
Z_s=(Z-Zmin)/(Zmax-Zmin)
print(Z_s)


[[0.90376529 0.8970677  0.84384658 1.         0.04953628]
 [0.27367333 0.47171812 0.73408292 0.29241762 0.3561089 ]
 [0.59102185 0.73452158 0.64363052 0.90616892 0.90268611]
 [0.19577022 0.38567744 0.         0.17568961 0.93372946]
 [0.56645183 0.02228482 0.41592652 0.49373533 0.95149914]]


In [23]:
color=np.dtype([("r",np.ubyte,1),
                ("g",np.ubyte,1),
                ("b",np.ubyte,1),
                ("a",np.ubyte,1)
               ])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [24]:
np.ones((3,4))
Z=np.dot(np.ones((5,3)),np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [25]:
#区域运算
Z=np.arange(11)
Z[(3<Z)&(Z<=8)]*=-1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [43]:
#为什么差1呢？？？
print(sum(range(5),-1))
print(np.sum(range(5),-1))
print("--------------")
print(sum(range(0)))
print(sum(range(0),-1))#非np得sum，从m开始计算求和。
print(sum(range(0),-2))
print(np.sum(range(0),-1))

9
10
--------------
0
-1
-2
0.0


In [33]:
Z=np.arange(5)
Z**Z

1j*Z
Z/0.2/0.2

array([  0.,  25.,  50.,  75., 100.])

In [34]:
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Love\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Love\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


In [35]:
np.array(0)

array(0)

In [44]:
Z=np.random.uniform(-10,+10,10)#随机数
print(np.copysign(np.ceil(np.abs(Z)),Z))#ceil四舍五入  

[ 5. -3.  1.  5. -8. -7. -3. -5. -3. -4.]


In [50]:
#np.info(np.random.uniform)
#np.info(np.ceil)
np.info(np.copysign)

copysign(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Change the sign of x1 to that of x2, element-wise.

If both arguments are arrays or sequences, they have to be of the same
length. If `x2` is a scalar, its sign will be copied to all elements of
`x1`.

Parameters
----------
x1 : array_like
    Values to change the sign of.
x2 : array_like
    The sign of `x2` is copied to `x1`.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only

In [52]:
#两个np.arrry中相同得元素
Z1=np.random.randint(0,10,10)
Z2=np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[3 4 7 9]


In [57]:
defaults=np.seterr(all="ignore")
Z=np.ones(1)/0
_=np.seterr(**defaults)
with np.errstate(divide="ignore"):
    Z=np.ones(1)/0
    print(Z)

[inf]


In [58]:
np.sqrt(-1)==np.emath.sqrt(-1)

False

In [59]:
np.info(np.emath)

Wrapper functions to more user-friendly calling of certain math functions
whose output data-type is different than the input data-type in certain
domains of the input.

For example, for functions like `log` with branch cuts, the versions in this
module provide the mathematically valid answers in the complex plane::

  >>> import math
  >>> from numpy.lib import scimath
  >>> scimath.log(-math.exp(1)) == (1+1j*math.pi)
  True

Similarly, `sqrt`, other base logarithms, `power` and trig functions are
correctly handled.  See their respective docstrings for specific examples.


In [62]:
yesterday=np.datetime64("today","D")-np.timedelta64(1,"D")
print(yesterday)
today=np.datetime64("today","D")
print(today)
tomorrow=np.datetime64("today","D")+np.timedelta64(1,"D")
print(tomorrow)

2019-06-22
2019-06-23
2019-06-24


In [69]:
#时间的范围
Z=np.arange("2016-07","2016-08",dtype="datetime64[D]")
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [74]:
A=np.ones(3)*1
B=np.ones(3)*2
C=np.ones(3)*3
x=np.add(A,B,out=B)
print(x)

[3. 3. 3.]


In [77]:
np.divide(A,2,out=A)

array([-0.5, -0.5, -0.5])

In [78]:
np.negative(A,out=A)

array([0.5, 0.5, 0.5])

In [79]:
np.multiply(A,B,out=A)

array([1.5, 1.5, 1.5])

In [85]:
#提取一个数字的整数部分
Z=np.random.uniform(0,10,10)
print(Z)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z.astype(int))
print(np.trunc(Z))

[3.88884378 3.31627723 9.15455258 0.95140764 3.05122885 5.57567587
 0.05356853 9.83744006 6.30747872 8.41512822]
[3. 3. 9. 0. 3. 5. 0. 9. 6. 8.]
[3. 3. 9. 0. 3. 5. 0. 9. 6. 8.]
[3 3 9 0 3 5 0 9 6 8]
[3. 3. 9. 0. 3. 5. 0. 9. 6. 8.]


In [88]:
Z=np.zeros((5,5))
Z+=np.arange(5)
print(Z)
Z=np.zeros((1,5))
print(np.arange(5))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[0 1 2 3 4]
[[0. 0. 0. 0. 0.]]


In [104]:
def generate():
    for x in range(10):
        yield x
Z=np.fromiter(generate(),dtype=float)
print(Z)
print(type(Z))
#print(np.info(np.fromiter))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
<class 'numpy.ndarray'>


In [106]:
Z=np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [108]:
Z=np.random.random(10)
Z.sort()
print(Z)

[0.09867397 0.31742898 0.36615831 0.44764714 0.65471204 0.67559
 0.68200144 0.84415045 0.84706288 0.8758089 ]


In [109]:
#对小数组做排序
Z=np.arange(10)
np.add.reduce(Z)

45

In [111]:
A=np.random.randint(0,2,5)
B=np.random.randint(0,2,5)
equal=np.allclose(A,B)
print(equal)
equal=np.array_equal(A,B)
print(equal)

False
False


In [114]:
#建立一个只读数组
Z=np.zeros(10)
Z.flags.writeable=False
#Z[0]=1
print(Z[0])

0.0


In [116]:
Z=np.random.random((10,2))
X,Y=Z[:,0],Z[:,1]
R=np.sqrt(X**2+Y**2)
T=np.arctan2(Y,X)
print(R)
print(T)

[0.98354533 0.60262592 0.15760951 1.16271667 1.04223896 0.83578502
 0.90901274 0.86297432 1.03361053 0.56587698]
[1.0706605  0.6981417  0.89013095 0.75546294 0.42751948 0.50994356
 0.12284901 0.21784281 1.25751271 1.32021181]


In [119]:
#替换最大值
Z=np.random.random(10)
Z[Z.argmax()]=0
print(Z)

[0.         0.49483672 0.92840576 0.20608799 0.69659299 0.65911495
 0.56995627 0.81937702 0.26907253 0.70316813]


In [121]:
Z=np.zeros((5,5),[("x",float),("y",float)])
Z["x"],Z["y"]=np.meshgrid(np.linspace(0,1,5)),np.linspace(0,1,5))

SyntaxError: invalid syntax (<ipython-input-121-c697aed40520>, line 2)