In [1]:
import numpy as np

In [2]:
print(np.__version__)
np.show_config()

1.15.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


In [3]:
Z=np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
print("%d bytes"%(Z.size*Z.itemsize))#内存大小
Z1=np.zeros(1000)
print(Z1.size,Z1.itemsize)
print("%d bytes"%(Z1.size*Z1.itemsize))#内存大小

80 bytes
1000 8
8000 bytes


In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [6]:
#单个赋值
Z=np.zeros(10)
Z[4]=1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
#范围值
Z=np.arange(10,40)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39]


In [8]:
Z1=np.arange(40)
Z2=Z[::-1]#逆转list
print(Z2)

[39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16
 15 14 13 12 11 10]


In [9]:
Z=np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
#找到非零索引
nz=np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [11]:
Z=np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
Z=np.random.random((3,3,3))
print(Z)

[[[0.67642343 0.17455694 0.92400377]
  [0.97057874 0.72675878 0.1832678 ]
  [0.37332778 0.8822369  0.66027134]]

 [[0.4792456  0.75783685 0.09755878]
  [0.64781144 0.16633618 0.37388717]
  [0.38901403 0.47547391 0.01103926]]

 [[0.70740046 0.34076498 0.32404108]
  [0.00620739 0.6518075  0.15286504]
  [0.47515709 0.03906352 0.53309787]]]


In [13]:
Z=np.random.random((10,10))
Zmin,Zmax=Z.min(),Z.max()
print(Zmin,Zmax)

0.013300769038110394 0.9994830041578211


In [14]:
Z=np.random.random(30)
m=Z.mean()
print(m)

0.508593556772054


In [15]:
#范围换值
Z=np.ones((10,10))
Z[1:-1,1:-1]=0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [16]:
#pad...扩充
Z=np.ones((5,5))
Z=np.pad(Z,pad_width=2,mode="constant",constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [17]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.inf)
print(np.nan-np.nan)
print(0.3==0.1*3)
print(0.1*3)
print(type(0.1*3))
print(type(0.3))
a=0.1*3
b=0.3
print(a-b)

nan
False
False
inf
nan
False
0.30000000000000004
<class 'float'>
<class 'float'>
5.551115123125783e-17


In [18]:
#对角线上赋值
Z=np.diag(1+np.arange(4),k=-1)
print(Z)
Z=np.diag(1+np.arange(5),k=0)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [19]:
Z=np.zeros((8,8),dtype=int)
print(Z)
Z[1::2,::2]=1
Z[::2,1::2]=1
print(Z)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [20]:
#求一个numpy 中第i个值得下标
print(np.unravel_index(1,(6,7,8)))
print(np.unravel_index(2,(6,7,8)))
print(np.unravel_index(3,(6,7,8)))
print(np.unravel_index(10,(6,7,8)))
print(np.unravel_index(10,(10,10)))
print(np.unravel_index(11,(10,10)))

(0, 0, 1)
(0, 0, 2)
(0, 0, 3)
(0, 1, 2)
(1, 0)
(1, 1)


In [21]:
Z=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [22]:
#均值归一化
Z=np.random.random((5,5))
Zmax,Zmin=Z.max(),Z.min()
Z_s=(Z-Zmin)/(Zmax-Zmin)
print(Z_s)


[[0.18724333 0.65229319 0.0189533  0.19871598 0.05848875]
 [0.98022833 0.75130115 0.47583425 0.62978783 0.48859986]
 [0.08894138 1.         0.22112368 0.6065828  0.06855032]
 [0.15919506 0.6737404  0.75436021 0.32605927 0.42054291]
 [0.46885544 0.         0.29514425 0.20600177 0.7567849 ]]


In [23]:
color=np.dtype([("r",np.ubyte,1),
                ("g",np.ubyte,1),
                ("b",np.ubyte,1),
                ("a",np.ubyte,1)
               ])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [24]:
np.ones((3,4))
Z=np.dot(np.ones((5,3)),np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [25]:
#区域运算
Z=np.arange(11)
Z[(3<Z)&(Z<=8)]*=-1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [26]:
#为什么差1呢？？？
print(sum(range(5),-1))
print(np.sum(range(5),-1))
print("--------------")
print(sum(range(0)))
print(sum(range(0),-1))#非np得sum，从m开始计算求和。
print(sum(range(0),-2))
print(np.sum(range(0),-1))

9
10
--------------
0
-1
-2
0.0


In [27]:
Z=np.arange(5)
Z**Z

1j*Z
Z/0.2/0.2

array([  0.,  25.,  50.,  75., 100.])

In [28]:
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Love\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Love\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


In [29]:
np.array(0)

array(0)

In [30]:
Z=np.random.uniform(-10,+10,10)#随机数
print(np.copysign(np.ceil(np.abs(Z)),Z))#ceil四舍五入  

[ 5. -7.  7.  1. 10.  9. -2.  5.  9. -5.]


In [31]:
#np.info(np.random.uniform)
#np.info(np.ceil)
np.info(np.copysign)

copysign(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Change the sign of x1 to that of x2, element-wise.

If both arguments are arrays or sequences, they have to be of the same
length. If `x2` is a scalar, its sign will be copied to all elements of
`x1`.

Parameters
----------
x1 : array_like
    Values to change the sign of.
x2 : array_like
    The sign of `x2` is copied to `x1`.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only

In [32]:
#两个np.arrry中相同得元素
Z1=np.random.randint(0,10,10)
Z2=np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[]


In [33]:
defaults=np.seterr(all="ignore")
Z=np.ones(1)/0
_=np.seterr(**defaults)
with np.errstate(divide="ignore"):
    Z=np.ones(1)/0
    print(Z)

[inf]


In [34]:
np.sqrt(-1)==np.emath.sqrt(-1)

C:\Love\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [35]:
np.info(np.emath)

Wrapper functions to more user-friendly calling of certain math functions
whose output data-type is different than the input data-type in certain
domains of the input.

For example, for functions like `log` with branch cuts, the versions in this
module provide the mathematically valid answers in the complex plane::

  >>> import math
  >>> from numpy.lib import scimath
  >>> scimath.log(-math.exp(1)) == (1+1j*math.pi)
  True

Similarly, `sqrt`, other base logarithms, `power` and trig functions are
correctly handled.  See their respective docstrings for specific examples.


In [36]:
yesterday=np.datetime64("today","D")-np.timedelta64(1,"D")
print(yesterday)
today=np.datetime64("today","D")
print(today)
tomorrow=np.datetime64("today","D")+np.timedelta64(1,"D")
print(tomorrow)

2019-06-25
2019-06-26
2019-06-27


In [37]:
#时间的范围
Z=np.arange("2016-07","2016-08",dtype="datetime64[D]")
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [38]:
A=np.ones(3)*1
B=np.ones(3)*2
C=np.ones(3)*3
x=np.add(A,B,out=B)
print(x)

[3. 3. 3.]


In [39]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

In [40]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

In [41]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [42]:
#提取一个数字的整数部分
Z=np.random.uniform(0,10,10)
print(Z)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z.astype(int))
print(np.trunc(Z))

[4.17659098 8.11023258 1.30642448 2.69161447 5.45328149 6.32127724
 3.18466373 5.27586713 9.25122801 8.80352496]
[4. 8. 1. 2. 5. 6. 3. 5. 9. 8.]
[4. 8. 1. 2. 5. 6. 3. 5. 9. 8.]
[4 8 1 2 5 6 3 5 9 8]
[4. 8. 1. 2. 5. 6. 3. 5. 9. 8.]


In [43]:
Z=np.zeros((5,5))
Z+=np.arange(5)
print(Z)
Z=np.zeros((1,5))
print(np.arange(5))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[0 1 2 3 4]
[[0. 0. 0. 0. 0.]]


In [44]:
def generate():
    for x in range(10):
        yield x
Z=np.fromiter(generate(),dtype=float)
print(Z)
print(type(Z))
#print(np.info(np.fromiter))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
<class 'numpy.ndarray'>


In [45]:
Z=np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [46]:
Z=np.random.random(10)
Z.sort()
print(Z)

[0.14795014 0.2059472  0.25983696 0.30979672 0.45249583 0.71692649
 0.79331955 0.81028921 0.85632645 0.9649999 ]


In [47]:
#对小数组做排序
Z=np.arange(10)
np.add.reduce(Z)

45

In [48]:
A=np.random.randint(0,2,5)
B=np.random.randint(0,2,5)
equal=np.allclose(A,B)
print(equal)
equal=np.array_equal(A,B)
print(equal)

False
False


In [49]:
#建立一个只读数组
Z=np.zeros(10)
Z.flags.writeable=False
#Z[0]=1
print(Z[0])

0.0


In [50]:
Z=np.random.random((10,2))
X,Y=Z[:,0],Z[:,1]
R=np.sqrt(X**2+Y**2)
T=np.arctan2(Y,X)
print(R)
print(T)

[0.70641626 1.16302395 0.4659974  0.54479976 0.97400128 0.63642088
 0.70124543 0.33127922 0.60358325 0.20346114]
[1.39790628 0.56027547 0.55720098 0.68829957 1.04078988 0.33613535
 0.24209741 1.22178417 0.80132154 0.18781887]


In [51]:
#替换最大值
Z=np.random.random(10)
Z[Z.argmax()]=0
print(Z)

[0.33461123 0.04130424 0.53814745 0.22326589 0.17025479 0.67344007
 0.29096987 0.3227599  0.37539026 0.        ]


In [52]:
Z=np.zeros((5,5),[("x",float),("y",float)])
print(Z)
Z["x"],Z["y"]=np.meshgrid(np.linspace(0,1,5)),np.linspace(0,1,5)#0--1分成5份
print(Z)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]]


In [53]:
#构建函数运算
X=np.arange(8)
Y=X+0.5
C=1.0/np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.163637117973


In [54]:
for dtype in [np.int8,np.int32,np.int64]:
    print(dtype," -- ",np.iinfo(dtype).min)
    print(dtype," -- ",np.iinfo(dtype).max)
for dtype in [np.float32,np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

<class 'numpy.int8'>  --  -128
<class 'numpy.int8'>  --  127
<class 'numpy.int32'>  --  -2147483648
<class 'numpy.int32'>  --  2147483647
<class 'numpy.int64'>  --  -9223372036854775808
<class 'numpy.int64'>  --  9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [55]:
#打印数组中的所有值
np.set_printoptions(threshold=2)##设置为np.nan是错误的啊？？？
Z=np.zeros((16,16))
print(Z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [56]:
#给定一个标量，找到一个数组中与该标量值最接近的数字
Z=np.arange(100)
v=np.random.uniform(0,100)
index=(np.abs(Z-v)).argmin()
print(v," ---> ",Z[index])

95.88132766541327  --->  96


In [57]:
#构建结构化数组，内部可以包含n个组合
Z=np.zeros(1,
           [
               ("position",[
                   ("x",float,1),
                   ("y",float,1)
               ]),
               ("color",[
                   ("r",float,1),
                   ("g",float,1),
                   ("b",float,1)
               ])
           ]
          )
print(Z)

[((0., 0.), (0., 0., 0.))]


In [58]:
# 
Z=np.random.random((10,2))
print("-------------")
print(Z)
X,Y=np.atleast_2d(Z[:,0],Z[:,1])
D=np.sqrt((X-X.T)**2+(Y-Y.T)**2)
print(D)
print(D.shape)

-------------
[[0.27071979 0.03902019]
 [0.0611413  0.34787429]
 [0.97386405 0.16142147]
 ...
 [0.14262683 0.80949285]
 [0.02752778 0.30655036]
 [0.46038042 0.11676793]]
[[0.         0.37324791 0.71371838 ... 0.78104797 0.36154494 0.20497772]
 [0.37324791 0.         0.93157258 ... 0.46875536 0.05326853 0.4613047 ]
 [0.71371838 0.93157258 0.         ... 1.054017   0.95739998 0.51542156]
 ...
 [0.78104797 0.46875536 1.054017   ... 0.         0.51594471 0.76212543]
 [0.36154494 0.05326853 0.95739998 ... 0.51594471 0.         0.47262964]
 [0.20497772 0.4613047  0.51542156 ... 0.76212543 0.47262964 0.        ]]
(10, 10)


In [59]:
# 整数转为32浮点数
Z=np.arange(10,dtype=np.int32)
print(Z)
Z=Z.astype(np.float32,copy=False)
print(Z)
print("------浮点数转为整数----------")
Z=np.arange(10,dtype=np.float32)
print(Z)
Z=Z.astype(np.int32,copy=False)
print(Z)

[0 1 2 ... 7 8 9]
[0. 1. 2. ... 7. 8. 9.]
------浮点数转为整数----------
[0. 1. 2. ... 7. 8. 9.]
[0 1 2 ... 7 8 9]


In [60]:
#生成一个二维的高斯分布数据
X,Y=np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D=np.sqrt(X*X+Y*Y)
sigma, mu=1.0,0.0
G=np.exp(-((D-mu)**2/(2.0*sigma**2)))
print(G)

[[0.36787944 0.44822088 0.51979489 ... 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 ... 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 ... 0.73444367 0.63331324 0.51979489]
 ...
 [0.51979489 0.63331324 0.73444367 ... 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 ... 0.63331324 0.54610814 0.44822088]
 [0.36787944 0.44822088 0.51979489 ... 0.51979489 0.44822088 0.36787944]]


In [61]:
#随机放置p个元素在数组中
n=10
p=3
Z=np.zeros((n,n))
np.put(Z,np.random.choice(range(n*n),p,replace=False),1)
print(Z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [62]:
X=np.random.rand(5,10)
print(X)
#减去X的每一行的均值
Y=X-X.mean(axis=1,keepdims=True)
print(Y)
Y=X-X.mean(axis=0,keepdims=True)
print(Y)

[[0.91785359 0.65580886 0.29425485 ... 0.34925137 0.8200936  0.88328648]
 [0.19115874 0.80755336 0.24919609 ... 0.30028305 0.24564106 0.84966958]
 [0.32818447 0.78856797 0.70411578 ... 0.46143136 0.70631991 0.32293394]
 [0.63230097 0.56732887 0.73835082 ... 0.70219181 0.55158738 0.04372185]
 [0.66669316 0.58117049 0.47366298 ... 0.23265814 0.6597222  0.56296337]]
[[ 0.33894429  0.07689955 -0.28465445 ... -0.22965793  0.2411843
   0.30437718]
 [-0.34473974  0.27165487 -0.28670239 ... -0.23561543 -0.29025743
   0.3137711 ]
 [-0.23262341  0.22776009  0.1433079  ... -0.09937651  0.14551203
  -0.23787394]
 [ 0.09943158  0.03445948  0.20548143 ...  0.16932242  0.01871799
  -0.48914754]
 [ 0.13145334  0.04593068 -0.06157684 ... -0.30258167  0.12448239
   0.02772356]]
[[ 0.37061541 -0.02427705 -0.19766126 ... -0.05991178  0.22342077
   0.35077144]
 [-0.35607944  0.12746745 -0.24272001 ... -0.10888009 -0.35103177
   0.31715454]
 [-0.21905372  0.10848206  0.21219968 ...  0.05226821  0.10964708
 

In [63]:
Z=np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,2].argsort()])#按照所有行，第n列进行排序~~~!!!!很重要，省去了构建dict！！！

[[8 5 2]
 [4 2 1]
 [5 3 8]]
[[4 2 1]
 [8 5 2]
 [5 3 8]]


In [64]:
Z=np.random.randint(0,2,(3,10))
print(Z)
print((~Z.any(axis=0)).any())#判断是否有空列
print((~Z.any(axis=1)).any())#判断是否有空行

[[0 1 0 ... 0 1 0]
 [1 1 0 ... 1 0 0]
 [0 0 1 ... 1 0 1]]
True
False


In [65]:
Z=np.random.uniform(0,1,10)
z=0.5
m=Z.flat[np.abs(Z-z).argmin()]
print(m)

#给定一个标量，找到一个数组中与该标量值最接近的数字
Z=np.arange(100)
v=np.random.uniform(0,100)
index=(np.abs(Z-v)).argmin()
print(v," ---> ",Z[index])

0.5687672385253999
22.361449281427948  --->  22


In [66]:
# np.nditer做了什么不清楚........
A=np.arange(3).reshape(3,1)
B=np.arange(3).reshape(1,3)
print(A,B)
it=np.nditer([A,B,None])
print(it)
for x,y ,z in it:
    print(x,y,z)
    z[...]=x+y
print(z)
print(it.operands[2])

[[0]
 [1]
 [2]] [[0 1 2]]
0 0 8
0 1 5
0 2 2
1 0 4
1 1 2
1 2 1
2 0 5
2 1 3
2 2 8
4
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [67]:
## 不理解....
class NamedArray(np.ndarray):
    def __new__(cls,array,name="no name"):
        obj=np.asarray(array).view(cls)
        obj.name=name
        
        return obj
    def __array__finalize__(self,obj):
        if obj is None:
            return
        self.info=getattr(obj,"name","no name")
Z=NamedArray(np.arange(10),"range_10")
print(Z.name)


range_10


In [68]:
#64的题意没懂....
Z=np.ones(5)
print(Z)
I=np.random.randint(0,len(Z),6)
print(I)
Z0=Z
Z+=np.bincount(I,minlength=len(Z))
print(Z)
Z0=np.bincount(I,minlength=len(Z0))
print(Z0)

[1. 1. 1. 1. 1.]
[2 1 2 1 4 4]
[1. 3. 3. 1. 3.]
[0 2 2 0 2]


In [69]:
X=[1,2,3,4,5,6]#I为对应的索引
I=[1,3,7,3,4,1]#索引列表,X和I的长度必须相等
F=np.bincount(I,X)
for index, one in enumerate(F):
    print(index,"--",one)
#print(F)

0 -- 0.0
1 -- 7.0
2 -- 0.0
3 -- 6.0
4 -- 5.0
5 -- 0.0
6 -- 0.0
7 -- 3.0


In [70]:
#66
import numpy as np
w,h=16,16
I=np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F=I[...,0]*(256*256)+I[...,1]*256+I[...,2]
n=len(np.unique(F))
print(n)

8


In [71]:
print(I.shape)
print(I[0][0])

(16, 16, 3)
[1 1 1]


In [72]:
I[...,1].shape

(16, 16)

In [73]:
print(F.shape)
print(np.unique(F))

(16, 16)
[    0     1   256 ... 65537 65792 65793]


In [74]:
print(F)

[[65793     1 65792 ...     0 65536   256]
 [    1   256 65536 ...     1   256     1]
 [  257   256 65792 ... 65792     1     1]
 ...
 [    1 65536     1 ...   256     1   256]
 [  256 65792     1 ... 65792 65792 65536]
 [  256     1   257 ... 65536 65537 65792]]


In [75]:
a=np.array([1,1,2,3])
x=np.unique(a)
print(x)

[1 2 3]


In [76]:
#最后两轴的和
A=np.random.randint(0,10,(3,4,3,4))
print(A)
sum_A=A.sum(axis=(-2,-1))
print(sum_A)

[[[[9 5 4 2]
   [7 0 6 8]
   [5 2 0 4]]

  [[9 6 4 8]
   [8 6 1 2]
   [6 5 3 5]]

  [[4 5 5 7]
   [9 5 2 8]
   [8 3 5 5]]

  [[0 3 3 1]
   [9 3 4 5]
   [8 0 6 6]]]


 [[[1 8 8 3]
   [4 6 7 1]
   [1 7 5 5]]

  [[8 7 8 7]
   [0 7 5 9]
   [7 6 9 7]]

  [[5 0 3 5]
   [0 2 4 9]
   [0 3 2 0]]

  [[4 5 1 3]
   [8 6 4 8]
   [2 5 7 2]]]


 [[[4 3 7 2]
   [7 9 3 3]
   [0 8 9 7]]

  [[6 8 8 0]
   [2 2 5 7]
   [5 5 8 6]]

  [[7 0 2 7]
   [0 8 1 0]
   [1 3 6 6]]

  [[1 4 6 3]
   [2 7 9 5]
   [3 9 9 3]]]]
[[52 63 66 48]
 [56 80 33 55]
 [62 62 41 61]]


In [77]:
A=np.random.randint(0,10,(3,4))
print(A)
sum_A=A.sum(axis=(-2,-1))
print(sum_A)

[[1 5 9 5]
 [9 0 1 3]
 [6 1 4 8]]
52


In [78]:
#groupby的使用
D=np.random.uniform(0,1,100)
S=np.random.randint(0,10,100)
print(D)
print(S)
import pandas as pd
dd=pd.Series(D).groupby(S).mean()

[0.22937352 0.31667252 0.5124711  ... 0.11311436 0.45062344 0.62560637]
[0 7 3 ... 6 0 8]


In [79]:
dd

0    0.574606
1    0.352860
2    0.505710
3    0.592355
4    0.574982
5    0.304707
6    0.505510
7    0.586559
8    0.551686
9    0.416737
dtype: float64

In [80]:
#groupby，使用bincount来实现
F=np.bincount(S,D)
for index, one in enumerate(F):
    size_index=list(S).count(index)
    print(index,"--",one/size_index)
#print(F)

0 -- 0.5746060074548273
1 -- 0.35286034607102035
2 -- 0.5057103117220084
3 -- 0.5923548782147675
4 -- 0.5749824142492594
5 -- 0.304707401313969
6 -- 0.5055095870921579
7 -- 0.5865588642127635
8 -- 0.551685751772755
9 -- 0.4167371382503442


In [81]:
F=np.bincount(S,D)
D_counts=np.bincount(S)
D_means=F/D_counts
print(D_means)

[0.57460601 0.35286035 0.50571031 ... 0.58655886 0.55168575 0.41673714]


In [82]:
#获取对角线
A=np.random.uniform(0,1,(5,6))
B=np.random.uniform(0,1,(6,5))
x=np.dot(A,B)
print(x)
np.diag(np.dot(A,B))

[[1.44510326 2.23628344 2.25260989 1.69161705 1.30600127]
 [0.78576344 0.88560641 1.05785517 0.77118586 0.75281029]
 [1.49712763 1.63063914 1.9532977  1.31259572 1.0828972 ]
 [1.32331815 1.39375651 1.02445976 1.32602439 1.31861557]
 [0.90032863 0.95971769 1.20319256 0.72050507 0.6164548 ]]


array([1.44510326, 0.88560641, 1.9532977 , 1.32602439, 0.6164548 ])

In [83]:
#获取对角线，快的
np.sum(A*B.T,axis=1)

array([1.44510326, 0.88560641, 1.9532977 , 1.32602439, 0.6164548 ])

In [84]:
#更快
np.einsum("ij,ji->i",A,B)

array([1.44510326, 0.88560641, 1.9532977 , 1.32602439, 0.6164548 ])

In [85]:
Z=np.array([1,2,3,4,5])
nz=3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))#开辟原来数组的大小+每两个数中间多来的个数*（数字个数-1）
print(Z0)
Z0[::nz+1] = Z## (nz*Z的下标+1)
print(Z0)

[0. 0. 0. ... 0. 0. 0.]
[1. 0. 0. ... 0. 0. 5.]


In [86]:
A=np.ones((5,5,3))
B=2*np.ones((5,5))
print(A.shape)
print(B.shape)
print(A)
print(B)

(5, 5, 3)
(5, 5)
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [87]:
print(A*B[:,:,None])#最后以为赋值None

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [88]:
#任意两行互换
A=np.arange(25).reshape(5,5)
A[[0,1]]=A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [96]:
C=np.bincount([1,1,2,4,5])
print(len(C))
print(C)#0有0个，1有2个，2有1个，3有0个，4有1个，5有1个
A=np.repeat(np.arange(len(C)),C)
print(A)

6
[0 2 1 0 1 1]
[1 1 2 4 5]


In [104]:
# bool值取反
Z=np.random.randint(0,2,100)
print(Z)
np.logical_not(Z,out=Z)
print(Z)
np.negative(Z,out=Z)
print(Z)

[1 1 1 ... 0 1 1]
[0 0 0 ... 1 0 0]
[ 0  0  0 ... -1  0  0]


In [109]:
#计算矩阵的秩
Z=np.random.uniform(0,1,(10,10))
U,S,V=np.linalg.svd(Z)
rank=np.sum(S>1e-10)
print(rank)

10


In [110]:
#出现频率最高的数字
Z=np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

2


In [112]:
Z=np.random.randint(0,5,(10,10))
n=3
i=1+(Z.shape[0]-3)
j=1+(Z.shape[1]-3)
C=stride_tricks.as_strided(Z,shape=(i,j,n,n),strides=Z.strides+Z.strides)
print(C)

NameError: name 'stride_tricks' is not defined

In [113]:
class Symetric(np.ndarray):
     def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
     return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print (S)

[[ 8 13 13  9  8]
 [13  0 13  8  9]
 [13 13  7 42  8]
 [ 9  8 42  4 10]
 [ 8  9  8 10  8]]


In [118]:
#给一个数组，求第n个最大值
Z=np.arange(1000)
np.random.shuffle(Z)
print(Z)
n=5
print(Z[np.argsort(Z)[-n:]])

[804 296 212 ... 916 102 162]
[995 996 997 998 999]


In [119]:
print(Z[np.argpartition(-Z,n)[:n]])

[998 997 999 996 995]


In [120]:
x=np.random.rand()

In [122]:
print(x)
np.power(x,3)

0.27870233134584654


0.021648200660248064

In [168]:
A=np.random.randint(0,5,(2,3))
B=np.random.randint(0,5,(2,2))
A=np.array([[2, 0, 3],
            [3, 4, 2]])
B=np.array([[1, 4],
            [2, 4]])

In [169]:
### 不懂啊.........但是很重要...求另外一个矩阵中，每行是否出现了被比较矩阵的行
C=(A[...,np.newaxis,np.newaxis]==B)
rows=np.where(C.any((3,1)).all(1))[0]
print(rows)

[1]


In [165]:
print(C.any((3,1)))
print("------")

print(C.any((3,1)).all(0))
print(C.any((3,1)).all(1))

[[False  True]
 [ True  True]]
------
[False  True]
[False  True]


In [166]:
print(A)
print(A[...,0,0])
print(A[...,0,1])
print(A[...,0,2])
print(A[...,1,2])
print(A[1,2])
print(B)

[[2 0 3]
 [3 4 2]]
2
0
3
2
2
[[1 4]
 [2 4]]


In [167]:
print(C.shape)
print(C)

(2, 3, 2, 2)
[[[[False False]
   [ True False]]

  [[False False]
   [False False]]

  [[False False]
   [False False]]]


 [[[False False]
   [False False]]

  [[False  True]
   [False  True]]

  [[False False]
   [ True False]]]]


In [173]:
#提取出唯一的行，可以理解为去重。
Z = np.random.randint(0,2,(6,3))
print(Z)
print("..........")
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print (uZ)

[[0 1 1]
 [0 0 1]
 [0 1 1]
 [1 1 1]
 [1 1 0]
 [0 1 0]]
..........
[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 1 0]
 [1 1 1]]


In [180]:
X = np.random.randn(100) # random 1D array
X=np.arange(100)
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
print(idx)
print(idx.shape)
means = X[idx].mean(axis=1)  #给了1000个组数字，每组为随机从X中抽取100个，求得每组数字的均值
print(means)
print(means.shape)
confint = np.percentile(means, [2.5, 97.5])#求一组数据置信度为95的置信区间
print (confint)

[[68 31 73 ... 34 25 66]
 [29 98 66 ... 88  7 21]
 [29 38 81 ... 97 92 73]
 ...
 [10 45 78 ... 90 42  9]
 [ 2 73 68 ... 60 72 97]
 [40 47 21 ... 26 24 25]]
(1000, 100)
[49.76 51.08 50.18 ... 50.33 45.87 51.07]
(1000,)
[43.899   55.55025]


In [181]:
sen="如果我们忽略二分类问题中y的取值是一个离散的取值（0或1），我们继续使用线性回归来预测y的取值。这样做会导致y的取值并不为0或1。逻辑回归使用一个函数来归一化y值，使y的取值在区间(0,1)内，这个函数称为Logistic函数(logistic function)，也称为Sigmoid函数(sigmoid function)"
sen_list=[one for one in sen]

In [198]:
#一个文档中，某一个字出现的次数。
print(sen_list)
X=len(sen_list)*[1]
print(X)
X_dict=dict()
for i,one in enumerate(sen_list):
    if one in X_dict:
        pass
    else:
        X_dict[one]=i
sen_list_number=[X_dict[one]for one in sen_list] 
X_dict_reverse={v:k for k,v in X_dict.items() }
F=np.bincount(sen_list_number,X)
for index,one in enumerate(F):
    if one==0.0:
        continue
    print(index,"-- ",X_dict_reverse[index],"--",one)

['如', '果', '我', '们', '忽', '略', '二', '分', '类', '问', '题', '中', 'y', '的', '取', '值', '是', '一', '个', '离', '散', '的', '取', '值', '（', '0', '或', '1', '）', '，', '我', '们', '继', '续', '使', '用', '线', '性', '回', '归', '来', '预', '测', 'y', '的', '取', '值', '。', '这', '样', '做', '会', '导', '致', 'y', '的', '取', '值', '并', '不', '为', '0', '或', '1', '。', '逻', '辑', '回', '归', '使', '用', '一', '个', '函', '数', '来', '归', '一', '化', 'y', '值', '，', '使', 'y', '的', '取', '值', '在', '区', '间', '(', '0', ',', '1', ')', '内', '，', '这', '个', '函', '数', '称', '为', 'L', 'o', 'g', 'i', 's', 't', 'i', 'c', '函', '数', '(', 'l', 'o', 'g', 'i', 's', 't', 'i', 'c', ' ', 'f', 'u', 'n', 'c', 't', 'i', 'o', 'n', ')', '，', '也', '称', '为', 'S', 'i', 'g', 'm', 'o', 'i', 'd', '函', '数', '(', 's', 'i', 'g', 'm', 'o', 'i', 'd', ' ', 'f', 'u', 'n', 'c', 't', 'i', 'o', 'n', ')']
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [195]:
X=[1,1,1,1,1,1]#I为对应的索引
I=[1,3,7,3,4,1]#索引列表,X和I的长度必须相等
F=np.bincount(I,X)
for index, one in enumerate(F):
    print(index,"--",one)
#print(F)

0 -- 0.0
1 -- 2.0
2 -- 0.0
3 -- 2.0
4 -- 1.0
5 -- 0.0
6 -- 0.0
7 -- 1.0


In [197]:
X_dict
#X_dict_reverse

{' ': 122,
 '(': 90,
 ')': 94,
 ',': 92,
 '0': 25,
 '1': 27,
 'L': 103,
 'S': 136,
 'c': 110,
 'd': 142,
 'f': 123,
 'g': 105,
 'i': 106,
 'l': 114,
 'm': 139,
 'n': 125,
 'o': 104,
 's': 107,
 't': 108,
 'u': 124,
 'y': 12,
 '。': 47,
 '一': 17,
 '不': 59,
 '个': 18,
 '中': 11,
 '为': 60,
 '也': 133,
 '二': 6,
 '们': 3,
 '会': 51,
 '使': 34,
 '值': 15,
 '做': 50,
 '内': 95,
 '函': 73,
 '分': 7,
 '化': 78,
 '区': 88,
 '取': 14,
 '回': 38,
 '在': 87,
 '如': 0,
 '导': 52,
 '并': 58,
 '归': 39,
 '忽': 4,
 '性': 37,
 '我': 2,
 '或': 26,
 '散': 20,
 '数': 74,
 '是': 16,
 '来': 40,
 '果': 1,
 '样': 49,
 '测': 42,
 '用': 35,
 '略': 5,
 '的': 13,
 '离': 19,
 '称': 101,
 '类': 8,
 '线': 36,
 '继': 32,
 '续': 33,
 '致': 53,
 '辑': 66,
 '这': 48,
 '逻': 65,
 '问': 9,
 '间': 89,
 '预': 41,
 '题': 10,
 '（': 24,
 '）': 28,
 '，': 29}