In [25]:
import numpy as np

In [26]:
print(np.__version__)
np.show_config()

1.15.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


In [27]:
Z=np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [28]:
print("%d bytes"%(Z.size*Z.itemsize))#内存大小
Z1=np.zeros(1000)
print(Z1.size,Z1.itemsize)
print("%d bytes"%(Z1.size*Z1.itemsize))#内存大小

80 bytes
1000 8
8000 bytes


In [29]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [30]:
#单个赋值
Z=np.zeros(10)
Z[4]=1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [31]:
#范围值
Z=np.arange(10,40)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39]


In [32]:
Z1=np.arange(40)
Z2=Z[::-1]#逆转list
print(Z2)

[39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16
 15 14 13 12 11 10]


In [33]:
Z=np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [34]:
#找到非零索引
nz=np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [35]:
Z=np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
Z=np.random.random((3,3,3))
print(Z)

[[[0.07415421 0.07061232 0.14972396]
  [0.13386399 0.1848654  0.69281659]
  [0.19483162 0.13314871 0.05175525]]

 [[0.52523617 0.46220296 0.55403293]
  [0.46492707 0.92651927 0.66248938]
  [0.16012742 0.77296751 0.96066791]]

 [[0.66730183 0.67256441 0.196609  ]
  [0.53953961 0.07048836 0.74935467]
  [0.25107378 0.76409677 0.25698395]]]


In [37]:
Z=np.random.random((10,10))
Zmin,Zmax=Z.min(),Z.max()
print(Zmin,Zmax)

0.016326776782392693 0.9935000651819416


In [38]:
Z=np.random.random(30)
m=Z.mean()
print(m)

0.5704700961084861


In [39]:
#范围换值
Z=np.ones((10,10))
Z[1:-1,1:-1]=0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [40]:
#pad...扩充
Z=np.ones((5,5))
Z=np.pad(Z,pad_width=2,mode="constant",constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [41]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.inf)
print(np.nan-np.nan)
print(0.3==0.1*3)
print(0.1*3)
print(type(0.1*3))
print(type(0.3))
a=0.1*3
b=0.3
print(a-b)

nan
False
False
inf
nan
False
0.30000000000000004
<class 'float'>
<class 'float'>
5.551115123125783e-17


In [42]:
#对角线上赋值
Z=np.diag(1+np.arange(4),k=-1)
print(Z)
Z=np.diag(1+np.arange(5),k=0)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [43]:
Z=np.zeros((8,8),dtype=int)
print(Z)
Z[1::2,::2]=1
Z[::2,1::2]=1
print(Z)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [44]:
#求一个numpy 中第i个值得下标
print(np.unravel_index(1,(6,7,8)))
print(np.unravel_index(2,(6,7,8)))
print(np.unravel_index(3,(6,7,8)))
print(np.unravel_index(10,(6,7,8)))
print(np.unravel_index(10,(10,10)))
print(np.unravel_index(11,(10,10)))

(0, 0, 1)
(0, 0, 2)
(0, 0, 3)
(0, 1, 2)
(1, 0)
(1, 1)


In [45]:
Z=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [46]:
#均值归一化
Z=np.random.random((5,5))
Zmax,Zmin=Z.max(),Z.min()
Z_s=(Z-Zmin)/(Zmax-Zmin)
print(Z_s)


[[0.59868934 0.37435612 0.37589167 0.0558303  1.        ]
 [0.45544383 0.41364651 0.19913427 0.20722756 0.66446328]
 [0.35769918 0.66646892 0.98650953 0.7254262  0.7953895 ]
 [0.89298439 0.49384215 0.62903657 0.06694565 0.94863385]
 [0.78385662 0.         0.49693366 0.9371488  0.86800512]]


In [47]:
color=np.dtype([("r",np.ubyte,1),
                ("g",np.ubyte,1),
                ("b",np.ubyte,1),
                ("a",np.ubyte,1)
               ])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [48]:
np.ones((3,4))
Z=np.dot(np.ones((5,3)),np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [49]:
#区域运算
Z=np.arange(11)
Z[(3<Z)&(Z<=8)]*=-1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [50]:
#为什么差1呢？？？
print(sum(range(5),-1))
print(np.sum(range(5),-1))
print("--------------")
print(sum(range(0)))
print(sum(range(0),-1))#非np得sum，从m开始计算求和。
print(sum(range(0),-2))
print(np.sum(range(0),-1))

9
10
--------------
0
-1
-2
0.0


In [51]:
Z=np.arange(5)
Z**Z

1j*Z
Z/0.2/0.2

array([  0.,  25.,  50.,  75., 100.])

In [52]:
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Love\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Love\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


In [53]:
np.array(0)

array(0)

In [54]:
Z=np.random.uniform(-10,+10,10)#随机数
print(np.copysign(np.ceil(np.abs(Z)),Z))#ceil四舍五入  

[ 9.  4. -4.  7. -1. -5. -5.  2.  3. -1.]


In [55]:
#np.info(np.random.uniform)
#np.info(np.ceil)
np.info(np.copysign)

copysign(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Change the sign of x1 to that of x2, element-wise.

If both arguments are arrays or sequences, they have to be of the same
length. If `x2` is a scalar, its sign will be copied to all elements of
`x1`.

Parameters
----------
x1 : array_like
    Values to change the sign of.
x2 : array_like
    The sign of `x2` is copied to `x1`.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only

In [56]:
#两个np.arrry中相同得元素
Z1=np.random.randint(0,10,10)
Z2=np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 3 4 8]


In [57]:
defaults=np.seterr(all="ignore")
Z=np.ones(1)/0
_=np.seterr(**defaults)
with np.errstate(divide="ignore"):
    Z=np.ones(1)/0
    print(Z)

[inf]


In [58]:
np.sqrt(-1)==np.emath.sqrt(-1)

C:\Love\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [59]:
np.info(np.emath)

Wrapper functions to more user-friendly calling of certain math functions
whose output data-type is different than the input data-type in certain
domains of the input.

For example, for functions like `log` with branch cuts, the versions in this
module provide the mathematically valid answers in the complex plane::

  >>> import math
  >>> from numpy.lib import scimath
  >>> scimath.log(-math.exp(1)) == (1+1j*math.pi)
  True

Similarly, `sqrt`, other base logarithms, `power` and trig functions are
correctly handled.  See their respective docstrings for specific examples.


In [60]:
yesterday=np.datetime64("today","D")-np.timedelta64(1,"D")
print(yesterday)
today=np.datetime64("today","D")
print(today)
tomorrow=np.datetime64("today","D")+np.timedelta64(1,"D")
print(tomorrow)

2019-06-23
2019-06-24
2019-06-25


In [61]:
#时间的范围
Z=np.arange("2016-07","2016-08",dtype="datetime64[D]")
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [62]:
A=np.ones(3)*1
B=np.ones(3)*2
C=np.ones(3)*3
x=np.add(A,B,out=B)
print(x)

[3. 3. 3.]


In [63]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

In [64]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

In [65]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [66]:
#提取一个数字的整数部分
Z=np.random.uniform(0,10,10)
print(Z)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z.astype(int))
print(np.trunc(Z))

[2.9790273  9.79409506 6.94928049 0.56683989 0.28955537 2.88902994
 8.40596714 0.14551335 7.49020658 8.26021865]
[2. 9. 6. 0. 0. 2. 8. 0. 7. 8.]
[2. 9. 6. 0. 0. 2. 8. 0. 7. 8.]
[2 9 6 0 0 2 8 0 7 8]
[2. 9. 6. 0. 0. 2. 8. 0. 7. 8.]


In [67]:
Z=np.zeros((5,5))
Z+=np.arange(5)
print(Z)
Z=np.zeros((1,5))
print(np.arange(5))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[0 1 2 3 4]
[[0. 0. 0. 0. 0.]]


In [68]:
def generate():
    for x in range(10):
        yield x
Z=np.fromiter(generate(),dtype=float)
print(Z)
print(type(Z))
#print(np.info(np.fromiter))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
<class 'numpy.ndarray'>


In [69]:
Z=np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [70]:
Z=np.random.random(10)
Z.sort()
print(Z)

[0.04741605 0.27044398 0.28911561 0.30687667 0.35213057 0.46725593
 0.56712914 0.60007496 0.92287204 0.97153163]


In [71]:
#对小数组做排序
Z=np.arange(10)
np.add.reduce(Z)

45

In [72]:
A=np.random.randint(0,2,5)
B=np.random.randint(0,2,5)
equal=np.allclose(A,B)
print(equal)
equal=np.array_equal(A,B)
print(equal)

False
False


In [73]:
#建立一个只读数组
Z=np.zeros(10)
Z.flags.writeable=False
#Z[0]=1
print(Z[0])

0.0


In [74]:
Z=np.random.random((10,2))
X,Y=Z[:,0],Z[:,1]
R=np.sqrt(X**2+Y**2)
T=np.arctan2(Y,X)
print(R)
print(T)

[0.1623036  0.06902429 0.33405423 1.03219974 0.35697417 1.29001642
 1.15558771 0.52578819 0.51099223 0.44000028]
[0.0879739  0.85922269 1.48308737 1.06437765 0.15492242 0.78970909
 0.89017282 1.07494145 1.14232527 0.80258641]


In [75]:
#替换最大值
Z=np.random.random(10)
Z[Z.argmax()]=0
print(Z)

[0.08881572 0.34024987 0.02363477 0.04374372 0.40488676 0.09798354
 0.80847128 0.70185846 0.         0.16930376]


In [76]:
Z=np.zeros((5,5),[("x",float),("y",float)])
print(Z)
Z["x"],Z["y"]=np.meshgrid(np.linspace(0,1,5)),np.linspace(0,1,5)#0--1分成5份
print(Z)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]]


In [77]:
#构建函数运算
X=np.arange(8)
Y=X+0.5
C=1.0/np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.163637117973


In [78]:
for dtype in [np.int8,np.int32,np.int64]:
    print(dtype," -- ",np.iinfo(dtype).min)
    print(dtype," -- ",np.iinfo(dtype).max)
for dtype in [np.float32,np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

<class 'numpy.int8'>  --  -128
<class 'numpy.int8'>  --  127
<class 'numpy.int32'>  --  -2147483648
<class 'numpy.int32'>  --  2147483647
<class 'numpy.int64'>  --  -9223372036854775808
<class 'numpy.int64'>  --  9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [79]:
#打印数组中的所有值
np.set_printoptions(threshold=2)##设置为np.nan是错误的啊？？？
Z=np.zeros((16,16))
print(Z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [80]:
#给定一个标量，找到一个数组中与该标量值最接近的数字
Z=np.arange(100)
v=np.random.uniform(0,100)
index=(np.abs(Z-v)).argmin()
print(v," ---> ",Z[index])

73.12965457473032  --->  73


In [81]:
#构建结构化数组，内部可以包含n个组合
Z=np.zeros(1,
           [
               ("position",[
                   ("x",float,1),
                   ("y",float,1)
               ]),
               ("color",[
                   ("r",float,1),
                   ("g",float,1),
                   ("b",float,1)
               ])
           ]
          )
print(Z)

[((0., 0.), (0., 0., 0.))]


In [82]:
# 
Z=np.random.random((10,2))
print("-------------")
print(Z)
X,Y=np.atleast_2d(Z[:,0],Z[:,1])
D=np.sqrt((X-X.T)**2+(Y-Y.T)**2)
print(D)
print(D.shape)

-------------
[[0.43655212 0.76436302]
 [0.40079531 0.48887525]
 [0.74769103 0.1240321 ]
 ...
 [0.99733683 0.29677202]
 [0.51162686 0.68454723]
 [0.47370114 0.39494328]]
[[0.         0.2777986  0.71192072 ... 0.73015124 0.10957544 0.3712829 ]
 [0.2777986  0.         0.50343537 ... 0.62671001 0.22488031 0.11890532]
 [0.71192072 0.50343537 0.         ... 0.30358212 0.60819693 0.3853094 ]
 ...
 [0.73015124 0.62671001 0.30358212 ... 0.         0.62151732 0.5327588 ]
 [0.10957544 0.22488031 0.60819693 ... 0.62151732 0.         0.29207671]
 [0.3712829  0.11890532 0.3853094  ... 0.5327588  0.29207671 0.        ]]
(10, 10)


In [88]:
# 整数转为32浮点数
Z=np.arange(10,dtype=np.int32)
print(Z)
Z=Z.astype(np.float32,copy=False)
print(Z)
print("------浮点数转为整数----------")
Z=np.arange(10,dtype=np.float32)
print(Z)
Z=Z.astype(np.int32,copy=False)
print(Z)

[0 1 2 ... 7 8 9]
[0. 1. 2. ... 7. 8. 9.]
------浮点数转为整数----------
[0. 1. 2. ... 7. 8. 9.]
[0 1 2 ... 7 8 9]


In [90]:
#生成一个二维的高斯分布数据
X,Y=np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D=np.sqrt(X*X+Y*Y)
sigma, mu=1.0,0.0
G=np.exp(-((D-mu)**2/(2.0*sigma**2)))
print(G)

[[0.36787944 0.44822088 0.51979489 ... 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 ... 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 ... 0.73444367 0.63331324 0.51979489]
 ...
 [0.51979489 0.63331324 0.73444367 ... 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 ... 0.63331324 0.54610814 0.44822088]
 [0.36787944 0.44822088 0.51979489 ... 0.51979489 0.44822088 0.36787944]]


In [92]:
#随机放置p个元素在数组中
n=10
p=3
Z=np.zeros((n,n))
np.put(Z,np.random.choice(range(n*n),p,replace=False),1)
print(Z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [95]:
X=np.random.rand(5,10)
print(X)
#减去X的每一行的均值
Y=X-X.mean(axis=1,keepdims=True)
print(Y)
Y=X-X.mean(axis=0,keepdims=True)
print(Y)

[[0.82902084 0.86370533 0.31558551 ... 0.68678764 0.02502057 0.19780268]
 [0.50183119 0.77659867 0.45134627 ... 0.88808404 0.62192782 0.37942554]
 [0.77547543 0.04880797 0.10309099 ... 0.48755534 0.3082887  0.60198351]
 [0.33657782 0.11382087 0.52469892 ... 0.02409527 0.47669838 0.5043366 ]
 [0.14486749 0.66196416 0.20110115 ... 0.23445639 0.55106244 0.65003789]]
[[ 0.34096569  0.37565018 -0.17246964 ...  0.19873249 -0.46303458
  -0.29025247]
 [-0.18148036  0.09328712 -0.23196528 ...  0.20477249 -0.06138373
  -0.30388601]
 [ 0.44818624 -0.27848123 -0.22419821 ...  0.16026615 -0.0190005
   0.27469431]
 [-0.07380484 -0.29656179  0.11431627 ... -0.38628738  0.06631572
   0.09395394]
 [-0.22736048  0.2897362  -0.17112682 ... -0.13777158  0.17883447
   0.27780993]]
[[ 0.31146628  0.37072593 -0.00357906 ...  0.2225919  -0.37157901
  -0.26891456]
 [-0.01572337  0.28361927  0.1321817  ...  0.4238883   0.22532824
  -0.08729171]
 [ 0.25792088 -0.44417143 -0.21607358 ...  0.02335961 -0.08831088
 

In [100]:
Z=np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,2].argsort()])#按照所有行，第n列进行排序~~~!!!!很重要，省去了构建dict！！！

[[3 5 5]
 [2 0 6]
 [2 6 6]]
[[3 5 5]
 [2 0 6]
 [2 6 6]]


In [108]:
Z=np.random.randint(0,2,(3,10))
print(Z)
print((~Z.any(axis=0)).any())#判断是否有空列
print((~Z.any(axis=1)).any())#判断是否有空行

[[0 1 0 ... 0 1 1]
 [1 0 0 ... 0 0 1]
 [1 0 0 ... 0 1 0]]
True
False


In [110]:
Z=np.random.uniform(0,1,10)
z=0.5
m=Z.flat[np.abs(Z-z).argmin()]
print(m)

#给定一个标量，找到一个数组中与该标量值最接近的数字
Z=np.arange(100)
v=np.random.uniform(0,100)
index=(np.abs(Z-v)).argmin()
print(v," ---> ",Z[index])

0.4594230063842457
98.597598249746  --->  99


In [126]:
# np.nditer做了什么不清楚........
A=np.arange(3).reshape(3,1)
B=np.arange(3).reshape(1,3)
print(A,B)
it=np.nditer([A,B,None])
print(it)
for x,y ,z in it:
    print(x,y,z)
    z[...]=x+y
print(z)
print(it.operands[2])

[[0]
 [1]
 [2]] [[0 1 2]]
0 0 0
0 1 1
0 2 2
1 0 1
1 1 2
1 2 3
2 0 2
2 1 3
2 2 4
4
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [134]:
## 不理解....
class NamedArray(np.ndarray):
    def __new__(cls,array,name="no name"):
        obj=np.asarray(array).view(cls)
        obj.name=name
        
        return obj
    def __array__finalize__(self,obj):
        if obj is None:
            return
        self.info=getattr(obj,"name","no name")
Z=NamedArray(np.arange(10),"range_10")
print(Z.name)


range_10


In [145]:
#64的题意没懂....
Z=np.ones(5)
print(Z)
I=np.random.randint(0,len(Z),6)
print(I)
Z0=Z
Z+=np.bincount(I,minlength=len(Z))
print(Z)
Z0=np.bincount(I,minlength=len(Z0))
print(Z0)

[1. 1. 1. 1. 1.]
[1 2 0 2 2 0]
[3. 2. 4. 1. 1.]
[2 1 3 0 0]


In [158]:
X=[1,2,3,4,5,6]#I为对应的索引
I=[1,3,7,3,4,1]#索引列表,X和I的长度必须相等
F=np.bincount(I,X)
for index, one in enumerate(F):
    print(index,"--",one)
#print(F)

0 -- 0.0
1 -- 7.0
2 -- 0.0
3 -- 6.0
4 -- 5.0
5 -- 0.0
6 -- 0.0
7 -- 3.0
